#!/usr/bin/env bash
# ModelOps one-command local/server deploy helper (Milestone 1).
#
# Usage:
#   ./scripts/deploy.sh              # configure .env if missing, then compose up
#   ./scripts/deploy.sh --configure  # re-run interactive wizard, then deploy
#   ./scripts/deploy.sh --down       # stop compose services (keep volumes)
#
# Does not install Docker. Does not commit secrets.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"
COMPOSE_FILE="${ROOT_DIR}/deploy/compose/docker-compose.yml"

DO_CONFIGURE=0
DO_DOWN=0

usage() {
  cat <<'EOF'
Usage: ./scripts/deploy.sh [--configure|--down|--help]

  (default)     Create .env if missing, then docker compose up -d --build
  --configure   Re-run interactive .env wizard (reuse existing values as defaults)
  --down        Stop ModelOps compose services (volumes are preserved)
  --help        Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --configure) DO_CONFIGURE=1 ;;
    --down) DO_DOWN=1 ;;
    --help|-h) usage; exit 0 ;;
    *)
      echo "error: unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if [[ "${DO_CONFIGURE}" -eq 1 && "${DO_DOWN}" -eq 1 ]]; then
  echo "error: --configure and --down cannot be used together" >&2
  exit 2
fi

require_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "error: 'docker' command not found." >&2
    echo "Install Docker Desktop / Docker Engine, then re-run ./scripts/deploy.sh" >&2
    exit 1
  fi

  if ! docker info >/dev/null 2>&1; then
    echo "error: Docker daemon is not reachable." >&2
    echo "Start Docker and ensure this user can access it (e.g. docker group), then retry." >&2
    exit 1
  fi

  if ! docker compose version >/dev/null 2>&1; then
    echo "error: 'docker compose' is not available." >&2
    echo "Install Docker Compose V2 (docker compose plugin) and retry." >&2
    exit 1
  fi
}

compose() {
  docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" "$@"
}

# Read KEY=value from an env file without sourcing (avoids shell injection).
env_get() {
  local key="$1"
  local file="${2:-${ENV_FILE}}"
  local line
  if [[ ! -f "${file}" ]]; then
    echo ""
    return 0
  fi
  line="$(grep -E "^${key}=" "${file}" | tail -n 1 || true)"
  if [[ -z "${line}" ]]; then
    echo ""
    return 0
  fi
  printf '%s\n' "${line#*=}"
}

prompt_value() {
  local label="$1"
  local default="${2:-}"
  local value=""
  if [[ -n "${default}" ]]; then
    read -r -p "${label} [${default}]: " value || true
    if [[ -z "${value}" ]]; then
      value="${default}"
    fi
  else
    read -r -p "${label}: " value || true
  fi
  printf '%s\n' "${value}"
}

prompt_password() {
  local label="$1"
  local default="${2:-}"
  local value=""
  if [[ -n "${default}" ]]; then
    read -r -s -p "${label} [Enter=keep current / local default]: " value || true
  else
    read -r -s -p "${label} [Enter=local default 'modelops']: " value || true
  fi
  echo "" >&2
  if [[ -z "${value}" ]]; then
    if [[ -n "${default}" ]]; then
      value="${default}"
    else
      value="modelops"
    fi
  fi
  printf '%s\n' "${value}"
}

# Minimal URL-encoding for credentials embedded in DATABASE_URL.
urlencode() {
  local raw="$1"
  if command -v python3 >/dev/null 2>&1; then
    python3 -c 'import sys, urllib.parse; print(urllib.parse.quote(sys.argv[1], safe=""))' "${raw}"
  else
    # Fallback: reject characters that break URLs rather than writing a bad URL.
    if [[ "${raw}" =~ [^A-Za-z0-9._~-] ]]; then
      echo "error: POSTGRES_PASSWORD contains special characters and python3 is required to encode MODELOPS_DATABASE_URL." >&2
      exit 1
    fi
    printf '%s\n' "${raw}"
  fi
}

write_env_file() {
  local environment="$1"
  local backend_port="$2"
  local postgres_port="$3"
  local postgres_db="$4"
  local postgres_user="$5"
  local postgres_password="$6"
  local debug="$7"
  local encoded_user encoded_pass database_url
  encoded_user="$(urlencode "${postgres_user}")"
  encoded_pass="$(urlencode "${postgres_password}")"
  database_url="postgresql+asyncpg://${encoded_user}:${encoded_pass}@localhost:${postgres_port}/${postgres_db}"

  umask 077
  cat >"${ENV_FILE}" <<EOF
# Generated by scripts/deploy.sh — do not commit real secrets.
# Re-run: ./scripts/deploy.sh --configure

MODELOPS_ENVIRONMENT=${environment}
MODELOPS_DEBUG=${debug}
BACKEND_PORT=${backend_port}

POSTGRES_DB=${postgres_db}
POSTGRES_USER=${postgres_user}
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_PORT=${postgres_port}

# Host-side tools (pytest/alembic). Compose overrides host to "postgres" for the backend container.
MODELOPS_DATABASE_URL=${database_url}
EOF
  echo "Wrote ${ENV_FILE}"
}

run_configure_wizard() {
  local cur_env cur_backend_port cur_pg_port cur_pg_db cur_pg_user cur_pg_password cur_debug
  local environment backend_port postgres_port postgres_db postgres_user postgres_password debug

  echo "ModelOps interactive configuration"
  echo "Press Enter to accept the value in [brackets]."
  echo ""

  cur_env="$(env_get MODELOPS_ENVIRONMENT)"
  cur_backend_port="$(env_get BACKEND_PORT)"
  cur_pg_port="$(env_get POSTGRES_PORT)"
  cur_pg_db="$(env_get POSTGRES_DB)"
  cur_pg_user="$(env_get POSTGRES_USER)"
  cur_pg_password="$(env_get POSTGRES_PASSWORD)"
  cur_debug="$(env_get MODELOPS_DEBUG)"

  environment="$(prompt_value "MODELOPS_ENVIRONMENT" "${cur_env:-local}")"
  backend_port="$(prompt_value "BACKEND_PORT" "${cur_backend_port:-8000}")"
  postgres_port="$(prompt_value "POSTGRES_PORT" "${cur_pg_port:-5432}")"
  postgres_db="$(prompt_value "POSTGRES_DB" "${cur_pg_db:-modelops}")"
  postgres_user="$(prompt_value "POSTGRES_USER" "${cur_pg_user:-modelops}")"
  postgres_password="$(prompt_password "POSTGRES_PASSWORD" "${cur_pg_password}")"
  debug="$(prompt_value "MODELOPS_DEBUG" "${cur_debug:-false}")"

  write_env_file \
    "${environment}" \
    "${backend_port}" \
    "${postgres_port}" \
    "${postgres_db}" \
    "${postgres_user}" \
    "${postgres_password}" \
    "${debug}"
}

wait_for_http_ok() {
  local url="$1"
  local label="$2"
  local attempts="${3:-30}"
  local sleep_s="${4:-2}"
  local i body code
  for ((i = 1; i <= attempts; i++)); do
    code="$(curl -s -o /tmp/modelops_deploy_probe.body -w '%{http_code}' "${url}" || true)"
    body="$(cat /tmp/modelops_deploy_probe.body 2>/dev/null || true)"
    if [[ "${code}" == "200" ]]; then
      echo "${label}: OK"
      return 0
    fi
    echo "waiting for ${label} (${i}/${attempts}) HTTP ${code:-000}..."
    sleep "${sleep_s}"
  done
  echo "error: ${label} did not become ready at ${url}" >&2
  echo "last response: ${body:-<empty>}" >&2
  return 1
}

print_failure_diagnostics() {
  echo "" >&2
  echo "--- docker compose ps ---" >&2
  compose ps >&2 || true
  echo "" >&2
  echo "--- backend logs (last 80 lines) ---" >&2
  compose logs --tail=80 backend >&2 || true
}

# --- main ---

require_docker

if [[ ! -f "${COMPOSE_FILE}" ]]; then
  echo "error: compose file not found: ${COMPOSE_FILE}" >&2
  exit 1
fi

if [[ "${DO_DOWN}" -eq 1 ]]; then
  if [[ ! -f "${ENV_FILE}" ]]; then
    echo "error: ${ENV_FILE} not found; cannot target compose project env." >&2
    echo "Create it with ./scripts/deploy.sh --configure or deploy once first." >&2
    exit 1
  fi
  echo "Stopping ModelOps compose services (volumes preserved)..."
  compose down
  echo "ModelOps services stopped."
  exit 0
fi

if [[ "${DO_CONFIGURE}" -eq 1 || ! -f "${ENV_FILE}" ]]; then
  run_configure_wizard
else
  echo "Using existing ${ENV_FILE} (pass --configure to change)."
fi

BACKEND_PORT="$(env_get BACKEND_PORT)"
BACKEND_PORT="${BACKEND_PORT:-8000}"

echo "Starting ModelOps with docker compose..."
if ! compose up -d --build; then
  echo "error: docker compose up failed" >&2
  print_failure_diagnostics
  exit 1
fi

echo ""
compose ps
echo ""

HEALTH_URL="http://localhost:${BACKEND_PORT}/health"
READY_URL="http://localhost:${BACKEND_PORT}/ready"

if ! wait_for_http_ok "${HEALTH_URL}" "Health"; then
  print_failure_diagnostics
  exit 1
fi

if ! wait_for_http_ok "${READY_URL}" "Ready"; then
  print_failure_diagnostics
  exit 1
fi

cat <<EOF

ModelOps deployment completed
Backend: http://localhost:${BACKEND_PORT}
Health: OK
Ready: OK
EOF
