"""initial core schema

Revision ID: e4d44d930a4a
Revises: 
Create Date: 2026-09-18 06:15:32.186562
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4d44d930a4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_app',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_key', name='uq_client_app_key')
    )
    op.create_table('endpoint_alias',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('api_type', sa.String(length=32), nullable=False),
    sa.Column('traffic_state', sa.String(length=32), server_default=sa.text("'SERVING'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', name='uq_endpoint_alias_alias')
    )
    op.create_index('ix_endpoint_alias_type_enabled', 'endpoint_alias', ['api_type', 'is_enabled'], unique=False)
    op.create_table('model',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('license_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_model_slug')
    )
    op.create_index('ix_model_type_active', 'model', ['model_type', 'is_active'], unique=False)
    op.create_table('node',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('agent_base_url', sa.Text(), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cpu_model', sa.String(length=255), nullable=True),
    sa.Column('ram_total_mb', sa.BigInteger(), nullable=True),
    sa.Column('disk_total_mb', sa.BigInteger(), nullable=True),
    sa.Column('labels_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname', name='uq_node_hostname'),
    sa.UniqueConstraint('name', name='uq_node_name')
    )
    op.create_index('ix_node_last_heartbeat_at', 'node', ['last_heartbeat_at'], unique=False)
    op.create_index('ix_node_status', 'node', ['status'], unique=False)
    op.create_table('routing_state',
    sa.Column('id', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_routing_state_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpu_device',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('gpu_uuid', sa.String(length=100), nullable=False),
    sa.Column('device_index', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('vram_total_mb', sa.BigInteger(), nullable=False),
    sa.Column('compute_capability', sa.String(length=32), nullable=True),
    sa.Column('safety_margin_mb', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gpu_uuid', name='uq_gpu_device_gpu_uuid'),
    sa.UniqueConstraint('node_id', 'device_index', name='uq_gpu_device_node_index')
    )
    op.create_index('ix_gpu_device_node_status', 'gpu_device', ['node_id', 'status'], unique=False)
    op.create_table('model_version',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(length=150), nullable=False),
    sa.Column('source_repository', sa.Text(), nullable=True),
    sa.Column('source_revision', sa.String(length=255), nullable=True),
    sa.Column('quantization', sa.String(length=50), nullable=True),
    sa.Column('dtype', sa.String(length=50), nullable=True),
    sa.Column('runtime_type', sa.String(length=50), nullable=False),
    sa.Column('runtime_image', sa.Text(), nullable=False),
    sa.Column('runtime_image_digest', sa.String(length=255), nullable=True),
    sa.Column('served_model_name', sa.String(length=255), nullable=False),
    sa.Column('expected_idle_vram_mb', sa.BigInteger(), nullable=True),
    sa.Column('expected_peak_vram_mb', sa.BigInteger(), nullable=True),
    sa.Column('default_max_model_len', sa.Integer(), nullable=True),
    sa.Column('runtime_config_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version_label', 'source_revision', 'quantization', name='uq_model_version_identity')
    )
    op.create_index('ix_model_version_model_archived', 'model_version', ['model_id', 'archived_at'], unique=False)
    op.create_index('ix_model_version_runtime_type', 'model_version', ['runtime_type'], unique=False)
    op.create_table('node_resource_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_utilization_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ram_total_mb', sa.BigInteger(), nullable=True),
    sa.Column('ram_used_mb', sa.BigInteger(), nullable=True),
    sa.Column('ram_free_mb', sa.BigInteger(), nullable=True),
    sa.Column('disk_total_mb', sa.BigInteger(), nullable=True),
    sa.Column('disk_used_mb', sa.BigInteger(), nullable=True),
    sa.Column('disk_free_mb', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_node_resource_snapshot_node', 'node_resource_snapshot', ['node_id', sa.text('sampled_at DESC')], unique=False)
    op.create_table('deployment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('deployment_type', sa.String(length=32), nullable=False),
    sa.Column('desired_state', sa.String(length=32), nullable=False),
    sa.Column('runtime_status', sa.String(length=32), nullable=False),
    sa.Column('health_status', sa.String(length=32), nullable=False),
    sa.Column('container_id', sa.String(length=255), nullable=True),
    sa.Column('container_name', sa.String(length=255), nullable=True),
    sa.Column('upstream_base_url', sa.Text(), nullable=False),
    sa.Column('runtime_port', sa.Integer(), nullable=True),
    sa.Column('deployment_config_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("deployment_type <> 'MANAGED' OR container_name IS NOT NULL", name='ck_deployment_managed_container_name'),
    sa.CheckConstraint("deployment_type <> 'MANAGED' OR node_id IS NOT NULL", name='ck_deployment_managed_node'),
    sa.CheckConstraint('runtime_port IS NULL OR (runtime_port BETWEEN 1 AND 65535)', name='ck_deployment_runtime_port_range'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_deployment_name')
    )
    op.create_index('ix_deployment_model_version', 'deployment', ['model_version_id'], unique=False)
    op.create_index('ix_deployment_node_status', 'deployment', ['node_id', 'runtime_status', 'health_status'], unique=False)
    op.create_index('ix_deployment_type_retired', 'deployment', ['deployment_type', 'retired_at'], unique=False)
    op.create_index('uq_deployment_container_id', 'deployment', ['container_id'], unique=True, postgresql_where=sa.text('container_id IS NOT NULL'))
    op.create_index('uq_deployment_container_name_active', 'deployment', ['container_name'], unique=True, postgresql_where=sa.text('container_name IS NOT NULL AND retired_at IS NULL'))
    op.create_table('gpu_resource_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gpu_device_id', sa.UUID(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vram_total_mb', sa.BigInteger(), nullable=True),
    sa.Column('vram_used_mb', sa.BigInteger(), nullable=True),
    sa.Column('vram_free_mb', sa.BigInteger(), nullable=True),
    sa.Column('gpu_utilization_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('memory_utilization_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('power_w', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['gpu_device_id'], ['gpu_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gpu_resource_snapshot_device', 'gpu_resource_snapshot', ['gpu_device_id', sa.text('sampled_at DESC')], unique=False)
    op.create_table('model_artifact',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('revision', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_artifact_version', 'model_artifact', ['model_version_id'], unique=False)
    op.create_table('deployment_gpu_assignment',
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('gpu_device_id', sa.UUID(), nullable=False),
    sa.Column('device_order', sa.Integer(), nullable=False),
    sa.Column('expected_vram_mb', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.ForeignKeyConstraint(['gpu_device_id'], ['gpu_device.id'], ),
    sa.PrimaryKeyConstraint('deployment_id', 'gpu_device_id'),
    sa.UniqueConstraint('deployment_id', 'device_order', name='uq_deployment_gpu_order')
    )
    op.create_index('ix_deployment_gpu_assignment_gpu', 'deployment_gpu_assignment', ['gpu_device_id'], unique=False)
    op.create_table('deployment_resource_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('gpu_device_id', sa.UUID(), nullable=True),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_vram_mb', sa.BigInteger(), nullable=True),
    sa.Column('container_cpu_pct', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('container_memory_mb', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.ForeignKeyConstraint(['gpu_device_id'], ['gpu_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deployment_resource_snapshot_deployment', 'deployment_resource_snapshot', ['deployment_id', sa.text('sampled_at DESC')], unique=False)
    op.create_index('ix_deployment_resource_snapshot_gpu', 'deployment_resource_snapshot', ['gpu_device_id', sa.text('sampled_at DESC')], unique=False)
    op.create_table('health_check',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_check_deployment', 'health_check', ['deployment_id', sa.text('checked_at DESC')], unique=False)
    op.create_table('invocation_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_app_id', sa.UUID(), nullable=True),
    sa.Column('raw_client_key', sa.String(length=255), nullable=True),
    sa.Column('source_ip', postgresql.INET(), nullable=True),
    sa.Column('endpoint_alias_id', sa.UUID(), nullable=True),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('api_path', sa.String(length=255), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('request_bytes', sa.BigInteger(), nullable=True),
    sa.Column('response_bytes', sa.BigInteger(), nullable=True),
    sa.Column('is_streaming', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['client_app_id'], ['client_app.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.ForeignKeyConstraint(['endpoint_alias_id'], ['endpoint_alias.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', name='uq_invocation_log_request_id')
    )
    op.create_index('ix_invocation_log_alias', 'invocation_log', ['endpoint_alias_id', sa.text('requested_at DESC')], unique=False)
    op.create_index('ix_invocation_log_client', 'invocation_log', ['client_app_id', sa.text('requested_at DESC')], unique=False)
    op.create_index('ix_invocation_log_deployment', 'invocation_log', ['deployment_id', sa.text('requested_at DESC')], unique=False)
    op.create_index('ix_invocation_log_requested_at', 'invocation_log', [sa.text('requested_at DESC')], unique=False)
    op.create_index('ix_invocation_log_status', 'invocation_log', ['http_status', sa.text('requested_at DESC')], unique=False)
    op.create_table('node_model_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('model_artifact_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('verified_checksum', sa.String(length=255), nullable=True),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_artifact_id'], ['model_artifact.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'model_artifact_id', name='uq_node_model_cache')
    )
    op.create_index('ix_node_model_cache_node_status', 'node_model_cache', ['node_id', 'status'], unique=False)
    op.create_table('operation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('operation_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('switch_strategy', sa.String(length=32), nullable=True),
    sa.Column('endpoint_alias_id', sa.UUID(), nullable=True),
    sa.Column('source_deployment_id', sa.UUID(), nullable=True),
    sa.Column('target_deployment_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('request_reason', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_alias_id'], ['endpoint_alias.id'], ),
    sa.ForeignKeyConstraint(['source_deployment_id'], ['deployment.id'], ),
    sa.ForeignKeyConstraint(['target_deployment_id'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operation_alias_created', 'operation', ['endpoint_alias_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_operation_alias_status', 'operation', ['endpoint_alias_id', 'status'], unique=False)
    op.create_index('ix_operation_source_status', 'operation', ['source_deployment_id', 'status'], unique=False)
    op.create_index('ix_operation_status_created', 'operation', ['status', 'created_at'], unique=False)
    op.create_index('ix_operation_target_created', 'operation', ['target_deployment_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_operation_target_status', 'operation', ['target_deployment_id', 'status'], unique=False)
    op.create_index('uq_operation_idempotency_key', 'operation', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('operation_id', sa.UUID(), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id', sa.text('occurred_at DESC')], unique=False)
    op.create_index('ix_audit_log_occurred_at', 'audit_log', [sa.text('occurred_at DESC')], unique=False)
    op.create_index('ix_audit_log_operation', 'audit_log', ['operation_id'], unique=False)
    op.create_table('endpoint_route',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('endpoint_alias_id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rewrite_model_name', sa.String(length=255), nullable=True),
    sa.Column('operation_id', sa.UUID(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.ForeignKeyConstraint(['endpoint_alias_id'], ['endpoint_alias.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_endpoint_route_alias_activated', 'endpoint_route', ['endpoint_alias_id', sa.text('activated_at DESC')], unique=False)
    op.create_index('ix_endpoint_route_deployment_status', 'endpoint_route', ['deployment_id', 'status'], unique=False)
    op.create_index('ix_endpoint_route_operation', 'endpoint_route', ['operation_id'], unique=False)
    op.create_index('uq_endpoint_route_active_alias', 'endpoint_route', ['endpoint_alias_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('operation_job',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_by', sa.String(length=255), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id', name='uq_operation_job_operation')
    )
    op.create_index('ix_operation_job_claim', 'operation_job', ['status', 'available_at', 'priority', 'created_at'], unique=False)
    op.create_index('ix_operation_job_running_locked', 'operation_job', ['locked_at'], unique=False, postgresql_where=sa.text("status = 'RUNNING'"))
    op.create_table('operation_step',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('step_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_no', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id', 'step_code', 'attempt_no', name='uq_operation_step_identity')
    )
    op.create_index('ix_operation_step_seq', 'operation_step', ['operation_id', 'sequence_no'], unique=False)
    op.create_index('ix_operation_step_status', 'operation_step', ['operation_id', 'status'], unique=False)
    op.create_table('resource_preflight',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('target_model_version_id', sa.UUID(), nullable=False),
    sa.Column('source_deployment_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('required_peak_vram_mb', sa.BigInteger(), nullable=False),
    sa.Column('available_hot_vram_mb', sa.BigInteger(), nullable=False),
    sa.Column('reclaimable_vram_mb', sa.BigInteger(), nullable=False),
    sa.Column('available_after_reclaim_mb', sa.BigInteger(), nullable=False),
    sa.Column('safety_margin_mb', sa.BigInteger(), nullable=False),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.ForeignKeyConstraint(['source_deployment_id'], ['deployment.id'], ),
    sa.ForeignKeyConstraint(['target_model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_preflight_model_version', 'resource_preflight', ['target_model_version_id', sa.text('checked_at DESC')], unique=False)
    op.create_index('ix_resource_preflight_node', 'resource_preflight', ['node_id', sa.text('checked_at DESC')], unique=False)
    op.create_index('ix_resource_preflight_operation', 'resource_preflight', ['operation_id', sa.text('checked_at DESC')], unique=False)
    op.create_table('resource_preflight_gpu',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('resource_preflight_id', sa.UUID(), nullable=False),
    sa.Column('gpu_device_id', sa.UUID(), nullable=False),
    sa.Column('free_vram_mb', sa.BigInteger(), nullable=False),
    sa.Column('reclaimable_vram_mb', sa.BigInteger(), nullable=False),
    sa.Column('safety_margin_mb', sa.BigInteger(), nullable=False),
    sa.Column('required_vram_mb', sa.BigInteger(), nullable=False),
    sa.Column('available_hot_vram_mb', sa.BigInteger(), nullable=False),
    sa.Column('available_after_reclaim_mb', sa.BigInteger(), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['gpu_device_id'], ['gpu_device.id'], ),
    sa.ForeignKeyConstraint(['resource_preflight_id'], ['resource_preflight.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_preflight_id', 'gpu_device_id', name='uq_resource_preflight_gpu')
    )
    op.create_index('ix_resource_preflight_gpu_device', 'resource_preflight_gpu', ['gpu_device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resource_preflight_gpu_device', table_name='resource_preflight_gpu')
    op.drop_table('resource_preflight_gpu')
    op.drop_index('ix_resource_preflight_operation', table_name='resource_preflight')
    op.drop_index('ix_resource_preflight_node', table_name='resource_preflight')
    op.drop_index('ix_resource_preflight_model_version', table_name='resource_preflight')
    op.drop_table('resource_preflight')
    op.drop_index('ix_operation_step_status', table_name='operation_step')
    op.drop_index('ix_operation_step_seq', table_name='operation_step')
    op.drop_table('operation_step')
    op.drop_index('ix_operation_job_running_locked', table_name='operation_job', postgresql_where=sa.text("status = 'RUNNING'"))
    op.drop_index('ix_operation_job_claim', table_name='operation_job')
    op.drop_table('operation_job')
    op.drop_index('uq_endpoint_route_active_alias', table_name='endpoint_route', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_endpoint_route_operation', table_name='endpoint_route')
    op.drop_index('ix_endpoint_route_deployment_status', table_name='endpoint_route')
    op.drop_index('ix_endpoint_route_alias_activated', table_name='endpoint_route')
    op.drop_table('endpoint_route')
    op.drop_index('ix_audit_log_operation', table_name='audit_log')
    op.drop_index('ix_audit_log_occurred_at', table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('uq_operation_idempotency_key', table_name='operation', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_operation_target_status', table_name='operation')
    op.drop_index('ix_operation_target_created', table_name='operation')
    op.drop_index('ix_operation_status_created', table_name='operation')
    op.drop_index('ix_operation_source_status', table_name='operation')
    op.drop_index('ix_operation_alias_status', table_name='operation')
    op.drop_index('ix_operation_alias_created', table_name='operation')
    op.drop_table('operation')
    op.drop_index('ix_node_model_cache_node_status', table_name='node_model_cache')
    op.drop_table('node_model_cache')
    op.drop_index('ix_invocation_log_status', table_name='invocation_log')
    op.drop_index('ix_invocation_log_requested_at', table_name='invocation_log')
    op.drop_index('ix_invocation_log_deployment', table_name='invocation_log')
    op.drop_index('ix_invocation_log_client', table_name='invocation_log')
    op.drop_index('ix_invocation_log_alias', table_name='invocation_log')
    op.drop_table('invocation_log')
    op.drop_index('ix_health_check_deployment', table_name='health_check')
    op.drop_table('health_check')
    op.drop_index('ix_deployment_resource_snapshot_gpu', table_name='deployment_resource_snapshot')
    op.drop_index('ix_deployment_resource_snapshot_deployment', table_name='deployment_resource_snapshot')
    op.drop_table('deployment_resource_snapshot')
    op.drop_index('ix_deployment_gpu_assignment_gpu', table_name='deployment_gpu_assignment')
    op.drop_table('deployment_gpu_assignment')
    op.drop_index('ix_model_artifact_version', table_name='model_artifact')
    op.drop_table('model_artifact')
    op.drop_index('ix_gpu_resource_snapshot_device', table_name='gpu_resource_snapshot')
    op.drop_table('gpu_resource_snapshot')
    op.drop_index('uq_deployment_container_name_active', table_name='deployment', postgresql_where=sa.text('container_name IS NOT NULL AND retired_at IS NULL'))
    op.drop_index('uq_deployment_container_id', table_name='deployment', postgresql_where=sa.text('container_id IS NOT NULL'))
    op.drop_index('ix_deployment_type_retired', table_name='deployment')
    op.drop_index('ix_deployment_node_status', table_name='deployment')
    op.drop_index('ix_deployment_model_version', table_name='deployment')
    op.drop_table('deployment')
    op.drop_index('ix_node_resource_snapshot_node', table_name='node_resource_snapshot')
    op.drop_table('node_resource_snapshot')
    op.drop_index('ix_model_version_runtime_type', table_name='model_version')
    op.drop_index('ix_model_version_model_archived', table_name='model_version')
    op.drop_table('model_version')
    op.drop_index('ix_gpu_device_node_status', table_name='gpu_device')
    op.drop_table('gpu_device')
    op.drop_table('routing_state')
    op.drop_index('ix_node_status', table_name='node')
    op.drop_index('ix_node_last_heartbeat_at', table_name='node')
    op.drop_table('node')
    op.drop_index('ix_model_type_active', table_name='model')
    op.drop_table('model')
    op.drop_index('ix_endpoint_alias_type_enabled', table_name='endpoint_alias')
    op.drop_table('endpoint_alias')
    op.drop_table('client_app')
    # ### end Alembic commands ###
